version: '3.8'

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: montink_app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      SERVICE_NAME: app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: montink
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
